# Copyright (c) 2026 Broadcom. All Rights Reserved.
# Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
# and/or its subsidiaries.
#
# =============================================================================
#
# SOFTWARE LICENSE AGREEMENT
#
# Copyright (c) CA, Inc. All rights reserved.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license
# under CA, Inc.'s copyrights to use, copy, modify, and distribute this
# software in source code or binary form for use in connection with CA, Inc.
# products.
#
# This copyright notice shall be included in all copies or substantial
# portions of the software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#
# =============================================================================
@{
    RootModule           = 'VcfCheck.psm1'
    ModuleVersion        = '2.0.0.1007'
    GUID                 = 'b4e1f7d0-6a2c-4e3a-9b8f-2d7c5a1e9f43'
    Author               = 'VCF'
    CompanyName          = 'Broadcom'
    Description          = 'Lightweight PowerShell precheck engine for VMware Cloud Foundation upgrades, paired with a bundled local Python report viewer.'
    PowerShellVersion    = '7.4'
    RequiredModules      = @()

    FunctionsToExport    = @(
        'Add-VcfCheckEnvironment'
        'Clear-VcfCheckAriaAutomationBearerToken'
        'Clear-VcfCheckSubProgress'
        'Connect-VcfCheckAriaAutomation'
        'Connect-VcfCheckAriaAutomationEndpoint'
        'Connect-VcfCheckAriaOps'
        'Connect-VcfCheckAriaOpsEndpoint'
        'Connect-VcfCheckNsxManager'
        'Connect-VcfCheckSddcManager'
        'Connect-VcfCheckVCenter'
        'ConvertFrom-SecureStringViaBstr'
        'ConvertFrom-VcfCheckDfOutput'
        'ConvertTo-SecureStringForCredential'
        'ConvertTo-VcfCheckFriendlyVrslcmError'
        'ConvertTo-VcfCheckHtmlEncoded'
        'ConvertTo-VcfCheckHtmlRemediationEncoded'
        'ConvertTo-VcfCheckHumanReadableKb'
        'ConvertTo-VcfCheckLcmSoftwareSummary'
        'ConvertTo-VcfCheckNormalizedExpiryDateText'
        'ConvertTo-VcfCheckReportJson'
        'ConvertTo-VcfCheckSimpleVersion'
        'Disconnect-VcfCheckAll'
        'Disconnect-VcfCheckComponent'
        'Export-VcfCheckReportCsv'
        'Export-VcfCheckReportHtml'
        'Find-VcfCheckBomVersionForComponent'
        'Find-VcfCheckPythonInterpreter'
        'Format-VcfCheckDuration'
        'Format-VcfCheckHtmlDocument'
        'Format-VcfCheckHtmlDocumentHead'
        'Format-VcfCheckHtmlHostDetailCard'
        'Format-VcfCheckHtmlHostSummaryBar'
        'Format-VcfCheckHtmlNav'
        'Format-VcfCheckHtmlResultCard'
        'Format-VcfCheckHtmlRowsTable'
        'Format-VcfCheckHtmlRunSummary'
        'Format-VcfCheckHtmlSummaryTable'
        'Format-VcfCheckHtmlSummaryTile'
        'Get-VcfApplianceErrorCategory'
        'Get-VcfCheckAllVCenterFqdns'
        'Get-VcfCheckAriaAutomationBearerToken'
        'Get-VcfCheckAriaAutomationCredential'
        'Get-VcfCheckAriaAutomationRefreshToken'
        'Get-VcfCheckAriaAutomationTargets'
        'Get-VcfCheckAriaOpsAdapterInstances'
        'Get-VcfCheckAriaOpsAdapterResources'
        'Get-VcfCheckAriaOpsApiToken'
        'Get-VcfCheckAriaOpsCertificates'
        'Get-VcfCheckAriaOpsCollectors'
        'Get-VcfCheckAriaOpsCredential'
        'Get-VcfCheckAriaOpsCriticalAlerts'
        'Get-VcfCheckAriaOpsLicenseEntitlement'
        'Get-VcfCheckAriaOpsResourceStats'
        'Get-VcfCheckAriaOpsSelfMonitoringAdapterKind'
        'Get-VcfCheckAriaOpsSelfMonitoringResources'
        'Get-VcfCheckAriaOpsVersion'
        'Test-VcfAriaOpsLifecycleStatus'
        'Get-VcfCheckAriaOpsTargets'
        'Get-VcfCheckApplianceHealth'
        'Get-VcfCheckApplianceNetworkingProxy'
        'Get-VcfCheckApplianceStorageUsage'
        'Get-VcfCheckApplianceSystemStorage'
        'Get-VcfCheckApplianceUptime'
        'Get-VcfCheckBrownfieldTreatmentData'
        'Get-VcfCheckCatalog'
        'Get-VcfCheckCheckSetResultViaRest'
        'Get-VcfCheckClusterDatastoreInventory'
        'Get-VcfCheckClusterEnablementSoftware'
        'Get-VcfCheckClusterInventory'
        'Get-VcfCheckClusterLcmSoftware'
        'Get-VcfCheckClusterVMHostInventory'
        'Get-VcfCheckComponentCredential'
        'Get-VcfCheckCredential'
        'Get-VcfCheckDatastoreInventory'
        'Get-VcfCheckDomainCurrentBom'
        'Get-VcfCheckDomains'
        'Get-VcfCheckDrsRule'
        'Get-VcfCheckEnvironmentAriaAutomationEndpoints'
        'Get-VcfCheckEnvironmentAriaOpsEndpoints'
        'Get-VcfCheckEnvironments'
        'Get-VcfCheckEsxCpuCompatibilityData'
        'Get-VcfCheckEsxCpuDeprecationData'
        'Get-VcfCheckEsxHostHardwareDetail'
        'Get-VcfCheckHardDiskInventory'
        'Get-VcfCheckHealthSummarySubTaskList'
        'Get-VcfCheckHealthSummarySubTaskSignature'
        'Get-VcfCheckHostAdvancedSetting'
        'Get-VcfCheckHostsGroupedByCluster'
        'Get-VcfCheckHtmlHostCpuStatus'
        'Get-VcfCheckHtmlStatusClass'
        'Get-VcfCheckInteropMatrixCompatibilityVerdict'
        'Get-VcfCheckLogDirectory'
        'Get-VcfCheckMachineCertificate'
        'Get-VcfCheckManagementDomain'
        'Get-VcfCheckManagementDomainId'
        'Get-VcfCheckManagementDomainSizingEstimate'
        'Get-VcfCheckManagementNsxManagerFqdn'
        'Get-VcfCheckManagementVCenterFqdn'
        'Get-VcfCheckMarketingVersionAliasMap'
        'Get-VcfCheckNsxAlarm'
        'Get-VcfCheckNsxApiServiceConfig'
        'Get-VcfCheckNsxBackupHistory'
        'Get-VcfCheckNsxBackupTypeStatus'
        'Get-VcfCheckNsxEdgeCluster'
        'Get-VcfCheckNsxLatencyProfile'
        'Get-VcfCheckNsxNappRegistration'
        'Get-VcfCheckPsqlExecutablePath'
        'Get-VcfCheckReleaseBom'
        'Get-VcfCheckReportStylesheet'
        'Get-VcfCheckSddcManagerRootCredential'
        'Get-VcfCheckSddcType'
        'Get-VcfCheckServerStatus'
        'Get-VcfCheckSettings'
        'Get-VcfCheckSizingReferenceData'
        'Get-VcfCheckSizingSnapshotForVCenter'
        'Get-VcfCheckSupervisorCluster'
        'Get-VcfCheckSupervisorClusterSoftware'
        'Get-VcfCheckTcpListenerProcessId'
        'Get-VcfCheckThemePreference'
        'Get-VcfCheckTimestampedReportPath'
        'Get-VcfCheckTlsTrustErrorMessage'
        'Get-VcfCheckUiCheckRunRowSet'
        'Get-VcfCheckVCenterAdvancedSetting'
        'Get-VcfCheckVCenterApplianceSizeEvaluation'
        'Get-VcfCheckVCenterDomainName'
        'Get-VcfCheckVCenterDomainType'
        'Get-VcfCheckVCenterExtension'
        'Get-VcfCheckVCenterServices'
        'Get-VcfCheckVCenterSizeTier'
        'Get-VcfCheckVCenterSsoCredential'
        'Get-VcfCheckVCenterSsoDomainName'
        'Get-VcfCheckVcfVersion'
        'Get-VcfCheckVDSwitchInventory'
        'Get-VcfCheckVersionAliasMap'
        'Get-VcfCheckVMHostCpuInfo'
        'Get-VcfCheckVMHostInventory'
        'Get-VcfCheckVMHostNetworkDevices'
        'Get-VcfCheckVMHostScsiDevices'
        'Get-VcfCheckVMHostStorageAdapters'
        'Get-VcfCheckVMInventory'
        'Get-VcfCheckVMSnapshotInventory'
        'Get-VcfCheckVrslcmConnection'
        'Get-VcfCheckVrslcmDatacenterCredentialRows'
        'Get-VcfCheckVrslcmRootCredential'
        'Get-VcfCheckVsanClusterConfig'
        'Get-VcfCheckVsanClusterHealth'
        'Get-VcfCheckVsanDiskGroupInventory'
        'Get-VcfCheckVsanObjectInventory'
        'Initialize-VcfCheck'
        'Initialize-VcfCheckLogging'
        'Initialize-VcfCheckMonitoringItemDataRequest'
        'Invoke-VcfApplianceCommand'
        'Invoke-VcfCheck'
        'Invoke-VcfCheckAriaAutomationApi'
        'Invoke-VcfCheckAriaOpsApi'
        'Invoke-VcfCheckInteropMatrixUpgrades'
        'Invoke-VcfCheckNsxManagerApi'
        'Invoke-VcfCheckNsxtCheck'
        'Invoke-VcfCheckPersistBaseDirectory'
        'Invoke-VcfCheckPerVCenterCheck'
        'Invoke-VcfCheckWithTimeout'
        'Invoke-VcfCheckServerManager'
        'Invoke-VcfCheckVCenterApplianceCliCheck'
        'Invoke-VcfCheckVrslcmApi'
        'New-VcfCheckApplianceCommandFailureResult'
        'New-VcfCheckBomComplianceRow'
        'New-VcfCheckContext'
        'New-VcfCheckEnvironmentId'
        'New-VcfCheckHealthSummarySpec'
        'New-VcfCheckOwnerOnlyDirectory'
        'New-VcfCheckPerDomainResults'
        'New-VcfCheckResult'
        'New-VcfCheckVersionAliasClusterRowSet'
        'New-VcfCheckVersionAliasRow'
        'Protect-VcfCheckLogMessage'
        'Remove-VcfCheckEnvironment'
        'Resolve-VcfCheckActiveBaseDirectory'
        'Resolve-VcfCheckAllowInsecureTls'
        'Resolve-VcfCheckAriaAutomationEndpointCredentials'
        'Resolve-VcfCheckAriaOpsCollectorFqdn'
        'Resolve-VcfCheckAriaOpsEndpointCredentials'
        'Resolve-VcfCheckBaseDirectory'
        'Resolve-VcfCheckBomDestinationThreshold'
        'Resolve-VcfCheckCheckList'
        'Resolve-VcfCheckEsxCpuCompatibility'
        'Resolve-VcfCheckEsxCpuDeprecationStatus'
        'Resolve-VcfCheckInProgressHealthCheckId'
        'Resolve-VcfCheckInteropMatrixReleaseInFamily'
        'Resolve-VcfCheckMarketingVersionAliasKeyFromBuild'
        'Restart-VcfCheckServer'
        'Save-VcfCheckEnvironments'
        'Set-VcfCheckEnvironment'
        'Start-VcfCheckServer'
        'Stop-VcfCheckServer'
        'Test-VcfCheckBomVersionMatch'
        'Test-VcfCheckDependencies'
        'Test-VcfCheckEnvironmentIsValid'
        'Test-VcfCheckModuleUpdate'
        'Test-VcfCheckSddcManagerRootCredential'
        'Test-VcfCheckTcpConnectivity'
        'Write-LogMessage'
        'Write-VcfCheckRuntimeInfo'
        'Write-VcfCheckCheckOutcome'
        'Write-VcfCheckCheckProgress'
        'Write-VcfCheckConsoleSummary'
        'Write-VcfCheckHealthSummaryProgress'
        'Write-VcfCheckHealthSummarySubTaskLog'
        'Write-VcfCheckReport'
        'Write-VcfCheckSizingProgress'
        'Write-VcfCheckSubProgress'
        # Individual check functions (Test-Vcf<CheckId>) are exported via wildcard pattern
        # to support direct invocation by Pester unit tests without requiring explicit manifest entries.
        'Test-Vcf*'
    )

    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()

    FileList             = @(
        'Install-VcfCheckModule.ps1'
        'Config\settings.example.json'
        'Data\CheckCatalog.json'
        'Data\CheckDescription.json'
        'Data\EsxCpu\EsxCpuCompatibility.json'
        'Data\EsxCpu\EsxCpuDeprecation.json'
        'Data\Interoperability\Esx.json'
        'Data\Interoperability\Nsx.json'
        'Data\Interoperability\SddcManager.json'
        'Data\Interoperability\Vcenter.json'
        'Data\Interoperability\Vidm.json'
        'Data\Interoperability\Vra.json'
        'Data\Interoperability\Vrli.json'
        'Data\Interoperability\Vrni.json'
        'Data\Interoperability\Vro.json'
        'Data\Interoperability\Vrops.json'
        'Data\Interoperability\Vrslcm.json'
        'Data\MarketingVersionAliases\EsxMarketingVersionAliases.json'
        'Data\MarketingVersionAliases\VcenterMarketingVersionAliases.json'
        'Data\Sizing\ComponentUpgradeCoexistence.json'
        'Data\Sizing\VmsSizingReferences911.json'
        'Docs\README.html'
        'Private\ApplianceCommand.ps1'
        'Private\AriaAutomationHelpers.ps1'
        'Private\AriaOpsHelpers.ps1'
        'Private\BomHelpers.ps1'
        'Private\Catalog.ps1'
        'Private\Checks\Aria\Test-VcfAriaApplianceDiskSpace.ps1'
        'Private\Checks\Aria\Test-VcfVrslcmCertificateExpiration.ps1'
        'Private\Checks\Aria\Test-VcfVrslcmDiskSpace.ps1'
        'Private\Checks\Aria\Test-VcfVrslcmFetchProducts.ps1'
        'Private\Checks\Aria\Test-VcfVrslcmRootPasswordExpiration.ps1'
        'Private\Checks\AriaOps\Test-VcfAriaOpsAdapterCollectionStatus.ps1'
        'Private\Checks\AriaOps\Test-VcfAriaOpsCertificateExpiration.ps1'
        'Private\Checks\AriaOps\Test-VcfAriaOpsCollectorStatus.ps1'
        'Private\Checks\AriaOps\Test-VcfAriaOpsCollectorType.ps1'
        'Private\Checks\AriaOps\Test-VcfAriaOpsCriticalAlerts.ps1'
        'Private\Checks\AriaOps\Test-VcfAriaOpsLicensing.ps1'
        'Private\Checks\AriaOps\Test-VcfAriaOpsLifecycleStatus.ps1'
        'Private\Checks\AriaOps\Test-VcfAriaOpsSizingOverview.ps1'
        'Private\Checks\Esx\Test-VcfEsxExecInstalledOnlyCheck.ps1'
        'Private\Checks\Esx\Test-VcfEsxHardwareDetails.ps1'
        'Private\Checks\Esx\Test-VcfEsxImageProfile.ps1'
        'Private\Checks\Esx\Test-VcfEsxLockdownStatus.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtAlarms.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtBackupHistory.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtCheckApiRate.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtCheckNappIntelligence.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtCheckNodeInstallUpgrade.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtComputeManagerStatus.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtDiskSpace.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtFederationCheck.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtLatencyProfileCheck.ps1'
        'Private\Checks\Nsxt\Test-VcfNsxtPasswordExpiration.ps1'
        'Private\Checks\Sample\Test-VcfSampleCheck.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcBomCheck.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcCheckAsyncPatchedApplied.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcCheckCpuCoresAndVsanTib.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcCheckFailedTasks.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcCheckHealthSummary.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcCheckLicenseKey.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcCheckRepositories.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcCheckUi.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcCheckVlcmVum.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcClusterResourceUtilization.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcLockTable.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcManagerDiskSpace.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcManifestPollingCheck.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcVersionAliasCheck.ps1'
        'Private\Checks\SddcManager\Test-VcfSddcVxManagerTable.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterApplianceSizeCheck.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterCheckDatastoreSpace.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterCheckDiskSpaceInodeAndHprof.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterCheckDrsAndAffinityRules.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterCheckHosts.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterCheckHostsMemoryUsage.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterCheckProxy.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterCheckReplication.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterCRLs.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterDetectHcxplugin.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterDetectLegacyPlugin.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterDetectSupervisor.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterIpfixNetflowEnabled.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterMachineIdCheck.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterMachineSslMismatch.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterMultiwriterEnabledVm.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterOverallHealth.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterPasswordPolicyExpiry.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterRootCredentialsValidity.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterServiceStatusCheck.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterSnapshotSize.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterSupervisorNamespaces.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterVamiCheckStorage.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterVdsVersionCheck.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterVerifyCertificateExpirationdate.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterVmdirDatabaseSizeCheck.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterVmdirLocalStateCheck.ps1'
        'Private\Checks\VCenter\Test-VcfVcenterVsphereSupervisorClusterVersions.ps1'
        'Private\Checks\Vsan\Test-VcfVsanCheckDisksAndGroups.ps1'
        'Private\Checks\Vsan\Test-VcfVsanDiskformatVersionCheck.ps1'
        'Private\Checks\Vsan\Test-VcfVsanHealthCheck.ps1'
        'Private\Checks\Vsan\Test-VcfVsanInaccessibleObjects.ps1'
        'Private\Checks\Vsan\Test-VcfVsanWitnessnodeVersion.ps1'
        'Private\Connections.ps1'
        'Private\Environments.ps1'
        'Private\EsxCpuCompatibilityHelpers.ps1'
        'Private\InteropMatrixHelpers.ps1'
        'Private\InventoryHelpers.ps1'
        'Private\IoDeviceCompatibility.ps1'
        'Private\Logging.ps1'
        'Private\Models.ps1'
        'Private\NsxHelpers.ps1'
        'Private\NsxManagerApiHelpers.ps1'
        'Private\Orchestrator.ps1'
        'Private\Reporting.ps1'
        'Private\SecureStringHelpers.ps1'
        'Private\Settings.ps1'
        'Private\SizingEstimator.ps1'
        'Private\Tools.ps1'
        'Private\VrslcmHelpers.ps1'
        'Tools\Invoke-VcfCheckLauncher.ps1'
        'Tools\Invoke-VcfCheckSizingDetect.ps1'
        'Tools\Invoke-VcfCheckSizingEstimate.ps1'
        'Tools\Invoke-VcfCheckSizingWorker.ps1'
        'Tools\Invoke-VcfCheckValidateCredentials.ps1'
        'Tools\Invoke-VcfCheckVrslcmLockerDiagnostic.ps1'
        'Tools\Manage-VcfCheckServer.py'
        'Tools\Start-VcfCheckServer.py'
        'Tools\vcfcheck_server\__init__.py'
        'Tools\vcfcheck_server\check_catalog.py'
        'Tools\vcfcheck_server\environments.py'
        'Tools\vcfcheck_server\json_utils.py'
        'Tools\vcfcheck_server\logs.py'
        'Tools\vcfcheck_server\paths.py'
        'Tools\vcfcheck_server\sizing.py'
        'Tools\vcfcheck_server\vcf_release.py'
        'Tools\ui\common.js'
        'Tools\ui\environments.js'
        'Tools\ui\export.js'
        'Tools\ui\filters.js'
        'Tools\ui\fqdn-validation.js'
        'Tools\ui\health-checks.js'
        'Tools\ui\init.js'
        'Tools\ui\live-log-filter.js'
        'Tools\ui\logbundle-export.js'
        'Tools\ui\password-toggle.js'
        'Tools\ui\report-render.js'
        'Tools\ui\run-actions-polling.js'
        'Tools\ui\run-scan.js'
        'Tools\ui\sizing-wizard-core.js'
        'Tools\ui\sizing-wizard-detect.js'
        'Tools\ui\sizing-wizard-steps.js'
        'Tools\ui\state.js'
        'Tools\ui\theme.js'
        'Tools\ui\zip-writer.js'
        'Tools\vcf-check-ui.html'
        'VcfCheck.psd1'
        'VcfCheck.psm1'
    )

    PrivateData = @{
	PSData = @{
	  Tags = @('VMware', 'VCF', 'VCFCheck', 'Upgrade', 'VCF.Check', 'Windows', 'Linux', 'MacOS')
	   ProjectUri = 'https://github.com/vmware/vcfcheck'
	   LicenseUri = 'https://github.com/vmware/vcfcheck/blob/main/LICENSE.md'
	   HelpInfoURI = 'https://github.com/vmware/vcfcheck/blob/main/README.md'
        }
    }
}
